// 获取用户管理的列表数据
export const FETCH_AUTHORITY_MANAGEMENT_LIST_URL = '/auth/user/list';
export const FETCH_AUTHORITY_MANAGEMEN_LIST_ACTION = 'FETCH_AUTHORITY_MANAGEMEN_LIST_ACTION';

// 用户列表-新增
export const ADD_AUTHORITY_MANAGEMENT_LIST_URL = '/auth/user/add';
export const ADD_AUTHORITY_MANAGEMEN_LIST_ACTION = 'ADD_AUTHORITY_MANAGEMEN_LIST_ACTION';

//用户列表-编辑
export const UPDATE_AUTHORITY_MANAGEMENT_LIST_URL = '/auth/user/update';
export const UPDATE_AUTHORITY_MANAGEMEN_LIST_ACTION = 'UPDATE_AUTHORITY_MANAGEMEN_LIST_ACTION';

//用户列表-重置密码
export const PASSWORD_AUTHORITY_MANAGEMENT_LIST_URL = '/auth/user/resetPassword';
export const PASSWORD_AUTHORITY_MANAGEMEN_LIST_ACTION = 'PASSWORD_AUTHORITY_MANAGEMEN_LIST_ACTION';

//用户列表-操作日志
export const SYSLOG_AUTHORITY_MANAGEMENT_LIST_URL = '/admin/sysLog/list';
export const SYSLOG_AUTHORITY_MANAGEMEN_LIST_ACTION = 'SYSLOG_AUTHORITY_MANAGEMEN_LIST_ACTION';

//用户列表-删除
export const DELETE_AUTHORITY_MANAGEMENT_LIST_URL = '/auth/user/del';
export const DELETE_AUTHORITY_MANAGEMEN_LIST_ACTION = 'DELETE_AUTHORITY_MANAGEMEN_LIST_ACTION';

//用户列表-启用状态
export const ENABLE_AUTHORITY_MANAGEMENT_LIST_URL = '/auth/user/enable';
export const ENABLE_AUTHORITY_MANAGEMEN_LIST_ACTION = 'ENABLE_AUTHORITY_MANAGEMEN_LIST_ACTION';
// 用户列表-禁用状态
export const DISABLE_AUTHORITY_MANAGEMENT_LIST_URL = '/auth/user/disable';
export const DISABLE_AUTHORITY_MANAGEMEN_LIST_ACTION = 'DISABLE_AUTHORITY_MANAGEMEN_LIST_ACTION';

// 获取用户-角色列表数据
export const FETCH_USER_ROLES_MANAGEMENT_LIST_URL = '/auth/userRole/list';
export const FETCH_USER_ROLES_MANAGEMEN_LIST_ACTION = 'FETCH_USER_ROLES_MANAGEMEN_LIST_ACTION';
