// 资源列表-查询
export const FETCH_RESOURCE_MANAGEMENT_LIST_URL = '/auth/resource/list';
export const FETCH_RESOURCE_MANAGEMEN_LIST_ACTION = 'FETCH_RESOURCE_MANAGEMEN_LIST_ACTION';

// 资源列表-新增
export const ADD_RESOURCE_MANAGEMENT_LIST_URL = '/auth/resource/add';
export const ADD_RESOURCE_MANAGEMEN_LIST_ACTION = 'ADD_RESOURCE_MANAGEMEN_LIST_ACTION';

// 资源列表-编辑
export const UPDATE_RESOURCE_MANAGEMENT_LIST_URL = '/auth/resource/update';
export const UPDATE_RESOURCE_MANAGEMEN_LIST_ACTION = 'UPDATE_RESOURCE_MANAGEMEN_LIST_ACTION';

// 资源列表-删除
export const DELETE_RESOURCE_MANAGEMENT_LIST_URL = '/auth/resource/del';
export const DELETE_RESOURCE_MANAGEMEN_LIST_ACTION = 'DELETE_RESOURCE_MANAGEMEN_LIST_ACTION';
